[colors]
ansi = [
    '#280c17',
    '#ed1d2f',
    '#d673d9',
    '#ff5c74',
    '#8896c8',
    '#ff72b3',
    '#d5396a',
    '#f6c9d5',
]
background = '#140409'
brights = [
    '#3d1626',
    '#ff4d4a',
    '#f993fb',
    '#ff7f92',
    '#a8b6ea',
    '#ff94d4',
    '#fa5d88',
    '#ffe0ee',
]
cursor_bg = '#fec8d5'
cursor_border = '#ff94d4'
cursor_fg = '#280c17'
foreground = '#fec8d5'
selection_bg = '#d963b9'
selection_fg = '#3d1626'

[metadata]
aliases = []
author = 'sailorfe'
name = 'Ghost Princess'
origin_url = 'https://github.com/sailorfe/ghost-princess'
