[colors]
ansi = [
    '#1c0817',
    '#ed1d2f',
    '#d673d9',
    '#ff5c74',
    '#8896c8',
    '#ff72b3',
    '#d5396a',
    '#ecc9ef',
]
background = '#0e030b'
brights = [
    '#2a0e25',
    '#ff4d4a',
    '#f993fb',
    '#ff7f92',
    '#a8b6ea',
    '#ff94d4',
    '#fa5d88',
    '#f9e3fb',
]
cursor_bg = '#fec8d5'
cursor_border = '#ff94d4'
cursor_fg = '#2a0e25'
foreground = '#fec8d5'
selection_bg = '#ff72b3'
selection_fg = '#2a0e25'

[metadata]
aliases = []
author = 'sailorfe'
name = 'Ghost Princess v2'
origin_url = 'https://github.com/sailorfe/ghost-princess'
